name: "Markdown to Confluence"
description: "Pushes directory of markdown files to Confluence with support for mermaidjs and Confluence links."
inputs:
  confluence_username:
    description: "confluence api username"
    required: true
  confluence_api_token:
    description: "confluence api token"
    required: true
  confluence_url:
    description: "confluence organization url"
    required: true
  confluence_space:
    description: "confluence space push content"
    required: true
  confluence_parent_pageid:
    description: "confluence page id to push content under"
    required: true
  markdown_dir:
    description: "mount point to use ar root of content to push"
    default: "./markdown"
runs:
  using: "docker"
  image: "Dockerfile"
