on: 
  push:
    branches:
      - master

jobs:
  build_push_test:
    runs-on: ubuntu-18.04
    name: Build and Push Action Docker
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: benwart/mdtocf
          tag_with_ref: true
          tag_with_sha: true
      - uses: ./ # uses the action in the root directory
        name: Test Markdown to Confluence
        id: mdtocf
        with:
          confluence-username: ${{ secrets.CONFLUENCE_USERNAME }}
          confluence-api-token: ${{ secrets.CONFLUENCE_API_TOKEN }}
          confluence-url: "https://opensesame.atlassian.net"
          confluence-space: "DevOps"
          confluence-parent-pageid: 758382711
          markdown-dir: './examples'
