on:
  push:
    tags:
      - "[0-9].[0-9].[0-9]"

jobs:
  build_push_test:
    runs-on: ubuntu-18.04
    name: Build and Push Action Docker
    steps:
      - name: Extract Git Info
        id: extract
        shell: bash
        run: |
          echo "##[set-output name=ref;]$(echo ${GITHUB_REF##*/})"
          echo "##[set-output name=sha;]$(echo ${GITHUB_SHA})"

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: benwart/mdtocf
          tags: ${{ steps.extract.outputs.ref }}
          tag_with_sha: true

      - uses: ./
        name: Test Markdown to Confluence
        id: mdtocf
        with:
          confluence_username: ${{ secrets.CONFLUENCE_USERNAME }}
          confluence_api_token: ${{ secrets.CONFLUENCE_API_TOKEN }}
          confluence_url: "https://opensesame.atlassian.net"
          confluence_space: "DevOps"
          confluence_parent_pageid: 758382711
          markdown_dir: "./examples"
